services:
  - type: web
    name: chatbot-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn chatbot_project.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
